// Pinned manifest shape fixtures: the exact tool names, required arrays, and
// enum arrays the MCP surface is allowed to expose. Split out of
// tool-manifest-budget.test.ts when that file hit the size ratchet.

export const EXPECTED_TOOL_NAMES = [
  "archive_work_item",
  "arm_heartbeat",
  "assign_work_item",
  "attach_to_work_item",
  "cancel_workflow_run",
  "comment_work_item",
  "compact_session",
  "cost_report",
  "create_label",
  "create_note",
  "create_work_item",
  "create_workflow",
  "decide_workflow_approval",
  "decide_work_item_approval",
  "delegate_task",
  "disable_workflow",
  "dispatch_work_item",
  "duplicate_workflow",
  "edit_work_item",
  "enable_workflow",
  "escalate_work_item_approval",
  "find_employees",
  "fire_workflow_event",
  "get_cron_run_history",
  "get_employee",
  "get_message_context",
  "get_work_item",
  "get_work_item_tree",
  "get_workflow",
  "get_workflow_run",
  "label_work_item",
  "land_on_work_item",
  "link_work_items",
  "list_cron_jobs",
  "list_departments",
  "list_employees",
  "list_files",
  "list_heartbeats",
  "list_labels",
  "list_notes",
  "list_sessions",
  "list_work_item_attachments",
  "list_work_item_comments",
  "list_work_items",
  "list_workflow_runs",
  "list_workflows",
  "publish_attachment",
  "read_file",
  "read_knowledge",
  "read_note",
  "read_session",
  "request_work_item_approval",
  "retire_workflow",
  "rerun_workflow_run",
  "retry_workflow_node",
  "search_knowledge",
  "search_messages",
  "search_sessions",
  "search_work_items",
  "send_to_session",
  "set_work_item_dispatch",
  "send_connector_message",
  "spawn_session",
  "start_workflow_run",
  "stop_heartbeat",
  "stop_session",
  "unlink_work_items",
  "update_note",
  "update_work_item",
  "update_workflow",
] as const;

export const EXPECTED_REQUIRED = {
  archive_work_item: ["id"],
  arm_heartbeat: ["message", "everySeconds"],
  assign_work_item: ["id", "assignee"],
  attach_to_work_item: ["id", "path"],
  cancel_workflow_run: ["workflowId", "runId"],
  comment_work_item: ["id", "body"],
  compact_session: ["goal", "done", "next"],
  cost_report: [],
  create_label: ["name"],
  create_note: ["title"],
  create_work_item: ["title"],
  create_workflow: ["id", "title"],
  decide_workflow_approval: ["workflowId", "runId", "nodeId", "decision", "expectedRevision"],
  decide_work_item_approval: ["id", "decision"],
  delegate_task: ["task"],
  disable_workflow: ["workflowId", "expectedRevision"],
  dispatch_work_item: ["id"],
  duplicate_workflow: ["sourceId", "id", "title"],
  edit_work_item: ["id"],
  enable_workflow: ["workflowId", "expectedRevision"],
  escalate_work_item_approval: ["id"],
  find_employees: [],
  fire_workflow_event: ["eventName", "fireId", "payload"],
  get_cron_run_history: ["id"],
  get_employee: ["name"],
  get_message_context: ["sessionId", "messageId"],
  get_work_item: ["id"],
  get_work_item_tree: ["id"],
  get_workflow: ["workflowId"],
  get_workflow_run: ["workflowId", "runId"],
  land_on_work_item: ["id"],
  label_work_item: ["id", "labels"],
  link_work_items: ["srcId", "dstId", "kind"],
  list_cron_jobs: [],
  list_departments: [],
  list_employees: [],
  list_files: [],
  list_heartbeats: [],
  list_labels: [],
  list_notes: [],
  list_sessions: [],
  list_work_item_attachments: ["id"],
  list_work_item_comments: ["id"],
  list_work_items: [],
  list_workflow_runs: ["workflowId"],
  list_workflows: [],
  publish_attachment: ["path"],
  read_file: ["path"],
  read_knowledge: ["path"],
  read_note: ["path"],
  read_session: ["sessionId"],
  request_work_item_approval: ["id", "request"],
  retire_workflow: ["workflowId", "expectedRevision"],
  rerun_workflow_run: ["workflowId", "runId", "definition", "idempotencyKey"],
  retry_workflow_node: ["workflowId", "runId", "nodeId", "idempotencyKey"],
  search_knowledge: ["query"],
  search_messages: ["query"],
  search_sessions: [],
  search_work_items: [],
  send_to_session: ["sessionId", "message"],
  set_work_item_dispatch: ["id"],
  send_connector_message: ["connector", "channel", "text"],
  spawn_session: ["prompt"],
  start_workflow_run: ["workflowId"],
  stop_heartbeat: ["id"],
  stop_session: ["sessionId"],
  unlink_work_items: ["srcId", "dstId", "kind"],
  update_note: ["path", "expectedRevision"],
  update_work_item: ["id", "status"],
  update_workflow: ["workflowId", "definition", "expectedRevision"],
} as const;

export const EXPECTED_ENUMS = {
  cost_report: [["properties.groupBy", ["employee", "day"]]],
  create_work_item: [["properties.priority", [0, 1, 2, 3]]],
  decide_workflow_approval: [["properties.decision", ["approve", "reject"]]],
  decide_work_item_approval: [["properties.decision", ["approve", "reject"]]],
  delegate_task: [["properties.intent", ["execute", "review"]]],
  edit_work_item: [["properties.priority", [0, 1, 2, 3]]],
  get_workflow_run: [["properties.view", ["full"]]],
  link_work_items: [["properties.kind", ["blocks", "relates", "duplicates"]]],
  list_sessions: [["properties.scope", ["children", "employee", "recent", "pinned"]]],
  label_work_item: [["properties.mode", ["add", "remove"]]],
  list_work_items: [
    ["properties.status", ["backlog", "assigned", "executing", "in_review", "done", "blocked", "escalated", "cancelled"]],
    ["properties.source", ["human", "delegation", "cron", "workflow", "session", "connector", "goal"]],
  ],
  search_messages: [["properties.role", ["user", "assistant"]]],
  search_sessions: [["properties.status", ["idle", "running", "error", "waiting", "interrupted"]]],
  rerun_workflow_run: [["properties.definition", ["original", "current"]]],
  search_work_items: [
    ["properties.status", ["backlog", "assigned", "executing", "in_review", "done", "blocked", "escalated", "cancelled"]],
    ["properties.source", ["human", "delegation", "cron", "workflow", "session", "connector", "goal"]],
  ],
  unlink_work_items: [["properties.kind", ["blocks", "relates", "duplicates"]]],
  update_work_item: [
    ["properties.status", ["backlog", "assigned", "executing", "in_review", "blocked", "escalated", "done"]],
    ["properties.blockKind", ["dependency", "needs_input", "capability", "transient"]],
  ],
} as const;
